# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iLPQt4F2O4EoEP1TeV4_Y9dLSzrrrKfL
"""

#realizavimas 1 budu
#4 laboratorinis darbas
failas = open("duom.txt")
sar1 = []
sar2 = []
for eilute in failas:
  apdorota = eilute.strip()
  #print(apdorota)
  dalys = apdorota.split()
  tel1= dalys[0]
  tel2= dalys[1]
  trukme = int(dalys[2])
  #tikrinimas ar yra vienodu numeriu ir netraukimas i sarasa
  if tel1 not in sar1:
    sar1.append(tel1)
    sar2.append(trukme)
  else:
    kur = sar1.index(tel1)
    sar2[kur] = sar2[kur]+trukme
    #print("reikia prideti ", kur)
  print(dalys[0],dalys[1],"=",trukme)
failas.close()
print(sar1)
print(sar2)
print("---------------------------------------------")
# 1 variantas
ind = 0
for elementas in sar1:
  tr = sar2[ind]
  print(elementas, tr)
  ind+=1
print("---------------------------------------------")
# 2 variantas
for ind2 in range(len(sar2)):
  tr = sar2[ind2]
  tl = sar1[ind2]
  print(ind2, tl, tr)

#realizavimas 2 budu
# 4 laboratorinis darbas
failas = open("duom.txt")
sar3 = {}
for eilute in failas:
  apdorota = eilute.strip()
  dalys = apdorota.split()
  tel1= dalys[0]
  tel2= dalys[1]
  trukme = int(dalys[2])
  if tel1 not in sar3:
    sar3[tel1]=trukme
  else:
    sar3[tel1]=sar3[tel1]+trukme
  print(dalys[0],dalys[1],"=",trukme)
failas.close()
print(sar3)
print("---------------------------------------------")
# 2 variantas
# rezultato isaugojimas i faila
fail2 = open("rez.txt", "w")
for el in sar3:
  print(el, sar3[el])
  fail2.write(el+" "+str(sar3[el])+"\n")

  